info:
  description: Training configuration repo

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka:eureka@eureka-undowned-fearlessness.cfapps.io/eureka

---

spring:
  profile: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
